create table "public"."questions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "content" text,
    "level" bigint
);


alter table "public"."questions" enable row level security;

create table "public"."survey_results" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "content" text
);


alter table "public"."survey_results" enable row level security;

CREATE UNIQUE INDEX questions_pkey ON public.questions USING btree (id);

CREATE UNIQUE INDEX survey_results_pkey ON public.survey_results USING btree (id);

alter table "public"."questions" add constraint "questions_pkey" PRIMARY KEY using index "questions_pkey";

alter table "public"."survey_results" add constraint "survey_results_pkey" PRIMARY KEY using index "survey_results_pkey";

grant delete on table "public"."questions" to "anon";

grant insert on table "public"."questions" to "anon";

grant references on table "public"."questions" to "anon";

grant select on table "public"."questions" to "anon";

grant trigger on table "public"."questions" to "anon";

grant truncate on table "public"."questions" to "anon";

grant update on table "public"."questions" to "anon";

grant delete on table "public"."questions" to "authenticated";

grant insert on table "public"."questions" to "authenticated";

grant references on table "public"."questions" to "authenticated";

grant select on table "public"."questions" to "authenticated";

grant trigger on table "public"."questions" to "authenticated";

grant truncate on table "public"."questions" to "authenticated";

grant update on table "public"."questions" to "authenticated";

grant delete on table "public"."questions" to "service_role";

grant insert on table "public"."questions" to "service_role";

grant references on table "public"."questions" to "service_role";

grant select on table "public"."questions" to "service_role";

grant trigger on table "public"."questions" to "service_role";

grant truncate on table "public"."questions" to "service_role";

grant update on table "public"."questions" to "service_role";

grant delete on table "public"."survey_results" to "anon";

grant insert on table "public"."survey_results" to "anon";

grant references on table "public"."survey_results" to "anon";

grant select on table "public"."survey_results" to "anon";

grant trigger on table "public"."survey_results" to "anon";

grant truncate on table "public"."survey_results" to "anon";

grant update on table "public"."survey_results" to "anon";

grant delete on table "public"."survey_results" to "authenticated";

grant insert on table "public"."survey_results" to "authenticated";

grant references on table "public"."survey_results" to "authenticated";

grant select on table "public"."survey_results" to "authenticated";

grant trigger on table "public"."survey_results" to "authenticated";

grant truncate on table "public"."survey_results" to "authenticated";

grant update on table "public"."survey_results" to "authenticated";

grant delete on table "public"."survey_results" to "service_role";

grant insert on table "public"."survey_results" to "service_role";

grant references on table "public"."survey_results" to "service_role";

grant select on table "public"."survey_results" to "service_role";

grant trigger on table "public"."survey_results" to "service_role";

grant truncate on table "public"."survey_results" to "service_role";

grant update on table "public"."survey_results" to "service_role";


