create table "public"."Question" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "content" text,
    "level" integer
);


alter table "public"."Question" enable row level security;

create table "public"."SurveyResult" (
    "id" integer generated by default as identity not null,
    "content" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."SurveyResult" enable row level security;

CREATE UNIQUE INDEX "Question_pkey" ON public."Question" USING btree (id);

CREATE UNIQUE INDEX "SurveyResult_pkey" ON public."SurveyResult" USING btree (id);

alter table "public"."Question" add constraint "Question_pkey" PRIMARY KEY using index "Question_pkey";

alter table "public"."SurveyResult" add constraint "SurveyResult_pkey" PRIMARY KEY using index "SurveyResult_pkey";

grant delete on table "public"."Question" to "anon";

grant insert on table "public"."Question" to "anon";

grant references on table "public"."Question" to "anon";

grant select on table "public"."Question" to "anon";

grant trigger on table "public"."Question" to "anon";

grant truncate on table "public"."Question" to "anon";

grant update on table "public"."Question" to "anon";

grant delete on table "public"."Question" to "authenticated";

grant insert on table "public"."Question" to "authenticated";

grant references on table "public"."Question" to "authenticated";

grant select on table "public"."Question" to "authenticated";

grant trigger on table "public"."Question" to "authenticated";

grant truncate on table "public"."Question" to "authenticated";

grant update on table "public"."Question" to "authenticated";

grant delete on table "public"."Question" to "service_role";

grant insert on table "public"."Question" to "service_role";

grant references on table "public"."Question" to "service_role";

grant select on table "public"."Question" to "service_role";

grant trigger on table "public"."Question" to "service_role";

grant truncate on table "public"."Question" to "service_role";

grant update on table "public"."Question" to "service_role";

grant delete on table "public"."SurveyResult" to "anon";

grant insert on table "public"."SurveyResult" to "anon";

grant references on table "public"."SurveyResult" to "anon";

grant select on table "public"."SurveyResult" to "anon";

grant trigger on table "public"."SurveyResult" to "anon";

grant truncate on table "public"."SurveyResult" to "anon";

grant update on table "public"."SurveyResult" to "anon";

grant delete on table "public"."SurveyResult" to "authenticated";

grant insert on table "public"."SurveyResult" to "authenticated";

grant references on table "public"."SurveyResult" to "authenticated";

grant select on table "public"."SurveyResult" to "authenticated";

grant trigger on table "public"."SurveyResult" to "authenticated";

grant truncate on table "public"."SurveyResult" to "authenticated";

grant update on table "public"."SurveyResult" to "authenticated";

grant delete on table "public"."SurveyResult" to "service_role";

grant insert on table "public"."SurveyResult" to "service_role";

grant references on table "public"."SurveyResult" to "service_role";

grant select on table "public"."SurveyResult" to "service_role";

grant trigger on table "public"."SurveyResult" to "service_role";

grant truncate on table "public"."SurveyResult" to "service_role";

grant update on table "public"."SurveyResult" to "service_role";


